spring.application.name=LuckPayAssignment

# Database Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# This will drop and recreate tables on startup
spring.jpa.generate-ddl=true
